const bcrypt_nodejs = require("bcrypt");
const Sequelize = require("sequelize");
const sequelize = require("../database/conn");

const birthSchema = sequelize.define("certificates", {
    // Column-1, user_id is an object with
    // properties like type, keys,
    // validation of column.
    id: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true,
    },

    BIRTH_ID: { type: Sequelize.STRING, allowNull: false },
    TS_DATE_OF_BIRTH: { type: Sequelize.STRING, allowNull: true },
    I_ULBOBJID: { type: Sequelize.STRING, allowNull: true },
    VC_SEX: { type: Sequelize.STRING, allowNull: true },
    VC_SURNAMECHILD: { type: Sequelize.STRING, allowNull: true },
    VC_NAME_CHILD: { type: Sequelize.STRING, allowNull: true },
    VC_AADHAR_NO: { type: Sequelize.STRING, allowNull: true },
    VC_SURNAME_FATHER: { type: Sequelize.STRING, allowNull: true },
    VC_NAME_FATHER: { type: Sequelize.STRING, allowNull: true },
    VC_AADHAR_NO_FATHER: { type: Sequelize.STRING, allowNull: true },
    VC_SURNAME_MOTHER: { type: Sequelize.STRING, allowNull: true },
    VC_NAME_MOTHER: { type: Sequelize.STRING, allowNull: true },
    VC_AADHAR_NO_MOTHER: { type: Sequelize.STRING, allowNull: true },
    VC_PLACE_OF_BIRTH: { type: Sequelize.STRING, allowNull: true },
    I_HOSPITAL_ID: { type: Sequelize.STRING, allowNull: true },
    VC_ADDRESS_LINE_1: { type: Sequelize.STRING, allowNull: true },
    VC_ADDRESS_LINE_2: { type: Sequelize.STRING, allowNull: true },
    VC_ADDRESS_LINE_3: { type: Sequelize.STRING, allowNull: true },
    VC_PIN_CODE: { type: Sequelize.STRING, allowNull: true },
    VC_ADDRESS_PARENT: { type: Sequelize.STRING, allowNull: true },
    VC_PERMANENT_ADDRESS_PARENT: { type: Sequelize.STRING, allowNull: true },
    VC_INFORMANT_SURNAME: { type: Sequelize.STRING, allowNull: true },
    VC_INFORMANT_NAME: { type: Sequelize.STRING, allowNull: true },
    VC_INFORMANT_ADDRESS: { type: Sequelize.STRING, allowNull: true },
    TS_INFORMED_DATE: { type: Sequelize.STRING, allowNull: true },
    VC_INFORMANT_SIGN: { type: Sequelize.STRING, allowNull: true },
    VC_INFORMANT_REMARKS: { type: Sequelize.STRING, allowNull: true },
    VC_MOBILE_NUMBER: { type: Sequelize.STRING, allowNull: true },
    VC_EMAIL_ID: { type: Sequelize.STRING, allowNull: true },
    VC_RESIDENCE: { type: Sequelize.STRING, allowNull: true },
    VC_NAME_TOWN: { type: Sequelize.STRING, allowNull: true },
    VC_NAME_MANDAL: { type: Sequelize.STRING, allowNull: true },
    VC_NAME_DISTRICT: { type: Sequelize.STRING, allowNull: true },
    VC_NAME_STATE: { type: Sequelize.STRING, allowNull: true },
    VC_RELIGION: { type: Sequelize.STRING, allowNull: true },
    VC_FATHER_LITERACY: { type: Sequelize.STRING, allowNull: true },
    VC_MOTHER_LITERACY: { type: Sequelize.STRING, allowNull: true },
    VC_FATHER_OCCUPATION: { type: Sequelize.STRING, allowNull: true },
    VC_MOTHER_OCCUPATION: { type: Sequelize.STRING, allowNull: true },
    VC_AGE_MOTHER: { type: Sequelize.STRING, allowNull: true },
    VC_AGE_MOTHER_DELIVERY: { type: Sequelize.STRING, allowNull: true },
    VC_NO_CHILD: { type: Sequelize.STRING, allowNull: true },
    VC_MEDICAL_ATTENTION: { type: Sequelize.STRING, allowNull: true },
    VC_DELIVERY_TYPE: { type: Sequelize.STRING, allowNull: true },
    VC_PREGNANCY_DURATION: { type: Sequelize.STRING, allowNull: true },
    VC_AFFIDAVIT: { type: Sequelize.STRING, allowNull: true },
    VC_NONAVAILABILITY: { type: Sequelize.STRING, allowNull: true },
    VC_MAGISTRATE_ORDER: { type: Sequelize.STRING, allowNull: true },
    VC_REMARKS: { type: Sequelize.STRING, allowNull: true },
    C_DELFLAG: { type: Sequelize.STRING, allowNull: true },
    TS_DTTM: { type: Sequelize.STRING, allowNull: true },
    I_CERATED_BY_ID: { type: Sequelize.STRING, allowNull: true },
    TS_CREATED_TIME: { type: Sequelize.STRING, allowNull: true },
    I_MODIFIED_BY_ID: { type: Sequelize.STRING, allowNull: true },
    TS_MODIFIED_TIME: { type: Sequelize.STRING, allowNull: true },
    VC_CREATED_IP: { type: Sequelize.STRING, allowNull: true },
    VC_MODIFIED_IP: { type: Sequelize.STRING, allowNull: true },
    I_APP_RECEIVED_ID: { type: Sequelize.STRING, allowNull: true },
    VC_STATUS: { type: Sequelize.STRING, allowNull: true },
    VC_MC_REMARKS: { type: Sequelize.STRING, allowNull: true },
    VC_ULB_VERIFIED: { type: Sequelize.STRING, allowNull: true },
    VC_CSC_REMARKS: { type: Sequelize.STRING, allowNull: true },
    REG_YEAR: { type: Sequelize.STRING, allowNull: true },
    TS_REG_DATE: { type: Sequelize.STRING, allowNull: true },
    TS_MC_APPROVED_DATE: { type: Sequelize.STRING, allowNull: true },
    I_LOCALITY: { type: Sequelize.STRING, allowNull: true },
    VC_CERT_NO: { type: Sequelize.STRING, allowNull: true },
    VC_COURT_CASE_NO: { type: Sequelize.STRING, allowNull: true },
    VC_REG_DESIGNATION: { type: Sequelize.STRING, allowNull: true },
    VC_REG_REMARKS: { type: Sequelize.STRING, allowNull: true },
    V_REG_SIGN: { type: Sequelize.STRING, allowNull: true },
    VC_HASHKEY: { type: Sequelize.STRING, allowNull: true },
    REG_NO: { type: Sequelize.STRING, allowNull: true },
    TS_MC_APPROVED_DT: { type: Sequelize.STRING, allowNull: true },
    ULB_STATUS: { type: Sequelize.STRING, allowNull: true },
    ULB_REMARKS: { type: Sequelize.STRING, allowNull: true },
    SI_REMARKS: { type: Sequelize.STRING, allowNull: true },
    MC_STATUS: { type: Sequelize.STRING, allowNull: true },
    MC_REMARKS: { type: Sequelize.STRING, allowNull: true },
    SI_STATUS: { type: Sequelize.STRING, allowNull: true },
    BIRTH_TYPE: { type: Sequelize.STRING, allowNull: true },
    VC_STATUS_DT: { type: Sequelize.STRING, allowNull: true },
    VC_ULB_STATUS_DT: { type: Sequelize.STRING, allowNull: true },
    VC_SI_STATUS_DT: { type: Sequelize.STRING, allowNull: true },
    VC_MC_STATUS_DT: { type: Sequelize.STRING, allowNull: true },
    CITIZEN_ENT_ID: { type: Sequelize.STRING, allowNull: true },
    I_DISTRICT_ID: { type: Sequelize.STRING, allowNull: true },
    I_MANDAL_ID: { type: Sequelize.STRING, allowNull: true },
    I_FAT_LITERACY_ID: { type: Sequelize.STRING, allowNull: true },
    I_MOT_LITERACY_ID: { type: Sequelize.STRING, allowNull: true },
    I_FAT_OCC_ID: { type: Sequelize.STRING, allowNull: true },
    I_MOT_OCC_ID: { type: Sequelize.STRING, allowNull: true },
    I_RELIGION_ID: { type: Sequelize.STRING, allowNull: true },
    I_DELIVERYTYPE_ID: { type: Sequelize.STRING, allowNull: true },
    I_ATTENBIRTH_ID: { type: Sequelize.STRING, allowNull: true },
    FORM_UPLOAD1: { type: Sequelize.STRING, allowNull: true },
    VC_COUNTRY_NAME: { type: Sequelize.STRING, allowNull: true },
    VC_COUNTRY_ADDRESS: { type: Sequelize.STRING, allowNull: true },
    VC_NATIONALITY: { type: Sequelize.STRING, allowNull: true },
    IS_BACKLOG: { type: Sequelize.STRING, allowNull: true },
    VC_CHILDWEIGHT: { type: Sequelize.STRING, allowNull: true },
    VC_SUPPORTING_DOC: { type: Sequelize.STRING, allowNull: true },
});
sequelize.sync();

module.exports = birthSchema;
